#version 430

layout (local_size_x = 1) in;

layout(binding = 0, offset = 0) uniform atomic_uint uCounter0;
layout(binding = 1, offset = 0) uniform atomic_uint uCounter1;
layout(binding = 1, offset = 4) uniform atomic_uint uCounter2;

void main() {
  atomicCounterIncrement(uCounter0);
  
  atomicCounterIncrement(uCounter1);
  atomicCounterIncrement(uCounter1);
  
  atomicCounterIncrement(uCounter2);
  atomicCounterIncrement(uCounter2);
  atomicCounterIncrement(uCounter2);
}
