
#include "basetsd.h"

#define _At_buffer_(target, iter, bound, annos)
#define _When_(expr, annos)
#define _Group_(annos)
#define _GrouP_(annos)
#define _On_failure_(annos)
#define _Use_decl_annotations_
#define _Notref_
#define _Pre_defensive_
#define _Post_defensive_
#define _In_defensive_(annotes)
#define _Out_defensive_(annotes)
#define _Inout_defensive_(annotes)
#define _Reserved_
#define _Const_
#define _In_
#define _In_opt_
#define _In_z_
#define _In_opt_z_
#define _In_reads_z_(size)
#define _In_reads_opt_z_(size)
#define _In_reads_or_z_(size)
#define _In_reads_or_z_opt_(size)
#define _In_reads_to_ptr_(ptr)
#define _In_reads_to_ptr_opt_(ptr)
#define _In_reads_to_ptr_z_(ptr)
#define _In_reads_to_ptr_opt_z_(ptr)
#define _Out_
#define _Out_opt_
#define _Out_writes_opt_z_(size)
#define _Out_writes_to_(size,count)
#define _Out_writes_bytes_to_(size,count)
#define _Out_writes_bytes_to_opt_(size,count)
#define _Out_writes_to_ptr_(ptr)
#define _Out_writes_to_ptr_opt_(ptr)
#define _Out_writes_to_ptr_z_(ptr)
#define _Out_writes_to_ptr_opt_z_(ptr)
#define _Inout_
#define _Inout_opt_
#define _Inout_z_
#define _Inout_opt_z_
#define _Inout_updates_opt_(size)
#define _Inout_updates_z_(size)
#define _Inout_updates_opt_z_(size)
#define _Inout_updates_to_(size,count)
#define _Inout_updates_to_opt_(size,count)
#define _Inout_updates_all_(size)
#define _Inout_updates_all_opt_(size)
#define _Inout_updates_bytes_opt_(size)
#define _Inout_updates_bytes_to_(size,count)
#define _Inout_updates_bytes_to_opt_(size,count)
#define _Inout_updates_bytes_all_(size)
#define _Inout_updates_bytes_all_opt_(size)
