# Github Actions configuration file
name: Build

on:
  push:
  release:
    types:
      - prereleased

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            package: WIX

          - os: ubuntu-18.04
            package: TGZ

          - os: macos-latest
            package: TGZ

    steps:
    - name: Setup Windows/MSVC
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86

    - name: Setup Linux/gcc-8
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install g++-8
        echo 'CC=gcc-8' >> $GITHUB_ENV
        echo 'CXX=g++-8' >> $GITHUB_ENV

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      with:
        version: '5.15.2'        

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_INSTALL_PREFIX=dist
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
    - name: Install
      run: cmake --install ${{github.workspace}}/build --config Release
    - name: Package
      run: cpack -G ${{ matrix.config.package }} --config ${{github.workspace}}/build/CPackConfig.cmake

    - name: Upload to Github release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "*.msi;*.tar.gz"
        tags: true
        draft: true
